In [1]:
import random
import numpy as np

from algorithms import Gradiente, Newton_1D, Newton_ND, BFGS

from obj_test_util5 import l, gradient_l, hessian_l

In [2]:
def prod(sample):
    out = 1
    for i in range(0, 5):
        out = out * sample[i] * (1 - sample[i])
    return out

def gen_sample():
    sample = []
    for i in range(0, 5):
        sample.append(random.uniform(0, 1))
    while prod(sample) < 0:
        sample = []
        for i in range(0, 5):
            sample.append(random.uniform(0, 1))
    return sample

In [3]:
samples = []

for i in range(0, 5):
    samples.append(gen_sample())

print(samples)

[[0.6893715691555151, 0.4074444126269239, 0.709072103084768, 0.5413882501298432, 0.061196511721083646], [0.10300949807703919, 0.892595837657775, 0.21827949981359962, 0.4375235157981323, 0.6944924078212453], [0.2717729723662978, 0.25445747167879285, 0.6112075564287425, 0.7707588209242283, 0.9002244297767696], [0.08805240420872706, 0.24068386791548202, 0.1443195239121855, 0.7310103668863412, 0.768547323813664], [0.9982885070249431, 0.3116850107186979, 0.6812012055813463, 0.1097371505564938, 0.2953642018401814]]


In [4]:
k = 100

for i in range(0, 5):
    print(f"Test for sample {i}")

    # x = np.array([0.5, 3, 8, 6, 7])
    x = samples[i]

    print("Calling gradient")
    xf = Gradiente(l, gradient_l, x, k)

    print(xf)
    print(f"Gradient result: {l(xf)}")

    print("Calling newton")
    xf = Newton_ND(l, gradient_l, hessian_l, x, k)

    print(xf)
    print(f"Newton result: {l(xf)}")

    dimensions = 5

    print("Calling BFGS")
    xf = BFGS(l, gradient_l, x, dimensions, k)

    print(xf)
    print(f"BFGS result: {l(xf)}")

Test for sample 0
Calling gradient
Armijo calls:400
[0.68937157 0.40744441 0.7090721  0.54138825 0.06119651]
Gradient result: 7.606066863351008e-05
Calling newton
[-1.11082903  1.06256669 -1.25888087  0.01462927  3.22050015]
Newton result: 0.022341142743515514
Calling BFGS
Else.
Matrix Hf is singular.
[-0.82481702  1.50143264  4.75087859  3.79903454 -1.24065764]
BFGS result: nan
Test for sample 1
Calling gradient


/var/home/pc-146/Documents/UFRJ/8° Período/Otimização/Trabalhos/Trabalho Prático/cos360_optimization_implementation_assignment/obj_test_util5.py:12: RuntimeWarning: invalid value encountered in sqrt
  return np.log(np.sqrt(h(x))) + p(x)


Armijo calls:400
[0.1030095  0.89259584 0.2182795  0.43752352 0.69449241]
Gradient result: 3.9459691331380675e-05
Calling newton
[0.1030095  0.89259584 0.2182795  0.43752352 0.69449241]
Newton result: 3.9459691331380675e-05
Calling BFGS
Else.
Matrix Hf is singular.
[ 0.69446384  0.9550034   0.91384483 -1.45880064  0.76161549]
BFGS result: -0.00023358724258827184
Test for sample 2
Calling gradient
Armijo calls:400
[0.27177297 0.25445747 0.61120756 0.77075882 0.90022443]
Gradient result: 7.07933765384121e-05
Calling newton
[-1.65002286  0.05843765  1.03123732  1.85422146  2.37190336]
Newton result: 0.01958409145893247
Calling BFGS
Else.
Matrix Hf is singular.
[0.58773485 2.4958326  1.36947886 1.26131299 0.9814226 ]
BFGS result: -0.0013696252931829707
Test for sample 3
Calling gradient
Armijo calls:400
[0.0880524  0.24068387 0.14431952 0.73101037 0.76854732]
Gradient result: 3.169316128231087e-05
Calling newton
[0.0880524  0.24068387 0.14431952 0.73101037 0.76854732]
Newton result: 3.1693