In [1]:
import random
import numpy as np

from algorithms import Gradiente, Newton_1D, Newton_ND, BFGS

from objective_function_util import f, gradient_f, hessian_f

In [2]:
noise = np.random.normal(0, 1, (2, 5))
print(noise)
print(noise.shape)
noise2 = np.random.normal(0, 1, noise.shape)
print(noise2)

[[-0.97236476  0.53436728 -0.37457163 -0.72457781 -0.09109139]
 [-0.3811735  -1.48416235  2.02941067  0.76083144 -1.25419408]]
(2, 5)
[[-1.3144908  -0.59497882 -1.45934255  0.30917719  0.23481049]
 [-0.37795825  0.38034459  0.46653554  0.86692539  0.19371763]]


In [3]:
a = np.exp(5)
print(a)

148.4131591025766


In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a + np.random.normal(0, 1, a.shape)
print(b)

[[1 2 3]
 [4 5 6]]
[[2.0225498  1.03911797 4.52043706]
 [3.71382464 5.48903529 5.47442629]]


In [5]:
def prod(sample):
    out = 1
    for i in range(0, 5):
        out = out * sample[i] * (1 - sample[i])
    return out

def gen_sample():
    sample = []
    for i in range(0, 5):
        sample.append(random.uniform(0, 1))
    while prod(sample) < 0:
        sample = []
        for i in range(0, 5):
            sample.append(random.uniform(0, 1))
    return sample

In [6]:
samples = []

for i in range(0, 5):
    samples.append(gen_sample())

print(samples)

[[0.21536326727373267, 0.8419150116623415, 0.303869090667939, 0.13681229372244008, 0.8884829070563746], [0.831057025258251, 0.9245799459866738, 0.36458609589415003, 0.9638005796371477, 0.33506527912853723], [0.3152558824784817, 0.08363552512640371, 0.7089443787522436, 0.21009366140700714, 0.23547910159947227], [0.7705799662852973, 0.4115116364508674, 0.8808038904785289, 0.26817107745927604, 0.6232123582343894], [0.9759966471351302, 0.3543037782919267, 0.6220926993018864, 0.001502775774515297, 0.9107464687720265]]


In [7]:
for sample in samples:
    print(f(sample))

0.007460925399236046
0.004198810241472412
0.010098884726405268
0.01439162378417945
0.0003920254699191024


In [8]:
x = np.array([0.5, 3, 8, 6, 7])

print(f(x))
print(gradient_f(x))
print(hessian_f(x))

print(np.linalg.det(hessian_f(x)))
print(np.linalg.norm(hessian_f(x)))

3.401425178799019
[0.         0.12249767 0.03937425 0.05389898 0.04549914]
[[-0.2939916356527391, -0.5005743444700167, -0.1608988964367911, -0.22025271156680737, -0.18592761366029195], [-0.0, 0.34495441772361296, -0.026815707719234857, -0.036707724344552606, -0.030987040031115836], [-0.0, -0.03127775881695764, 0.32213491581731474, -0.01376221387946136, -0.011617453274869979], [-0.0, -0.04170869366463398, -0.013406365820775205, 0.32450814401556966, -0.015491800504006904], [-0.0, -0.035748324803610926, -0.011490532972589222, -0.015729262913588803, 0.3230476958935666]]
-0.003290024872757404
0.941568092821632


In [9]:
x = np.array([0.5, 3, 8, 6, 7])

xf = Gradiente(f, gradient_f, x, 11000)

print(xf)
print(f(xf))

xf = Newton_ND(f, gradient_f, hessian_f, x, 11000)

print(xf)
print(f(xf))

dimensions = 5

xf = BFGS(f, gradient_f, x, dimensions, 11000)

print(xf)
print(f(xf))

Armijo calls:13
[0.5        0.48663109 7.57377982 5.40184394 6.5028746 ]
nan
Nan value in matrix Hf_inv
[1.60720175 2.58740602 7.82024297 5.76369113 6.79559939]
nan
Else.
Nan value in matrix p or q.
[-0.05993868  2.29032272  7.96226511  6.17255543  6.99008942]
nan


/var/home/pc-146/Documents/UFRJ/8° Período/Otimização/Trabalhos/Trabalho Prático/cos360_optimization_implementation_assignment/objective_function_util.py:7: RuntimeWarning: invalid value encountered in log
  return np.sqrt(np.log(prod + 1))
/var/home/pc-146/.conda/envs/work_env/lib/python3.12/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [10]:
for i in range(0, 5):
    print(f"Test for sample {i}")

    # x = np.array([0.5, 3, 8, 6, 7])
    x = samples[i]

    print("Results for gradient")
    xf = Gradiente(f, gradient_f, x, 11000)

    print(xf)
    print(f(xf))

    print("Results for newton")
    xf = Newton_ND(f, gradient_f, hessian_f, x, 11000)

    print(xf)
    print(f(xf))

    dimensions = 5

    print("Results for BFGS")
    xf = BFGS(f, gradient_f, x, dimensions, 11000)

    print(xf)
    print(f(xf))

Test for sample 0
Results for gradient
Armijo calls:4
[-225.55034696  345.16535336 -123.96887853 -412.06326738  526.40781956]
nan
Results for newton
Nan value in matrix Hf_inv
[-1.11204292  0.07893284 -1.89999147 -0.61333556  0.02393363]
nan
Results for BFGS
Elif.
Nan value in matrix p or q.
Matrix p: [[-225.76571023  344.32343835 -124.27274762 -412.20007967  525.51933666]
 [          nan           nan           nan           nan           nan]
 [          nan           nan           nan           nan           nan]
 [          nan           nan           nan           nan           nan]
 [          nan           nan           nan           nan           nan]]
Matrix q: [[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]
[nan nan nan nan nan]
nan
Test for sample 1
Results for gradient
Armijo calls:4
[ 562.4032545  1451.03783096 -138.84854313 3167.00264935 -175.97512095]
nan
Results for newton
Nan value in matrix Hf_inv
[  

/var/home/pc-146/Documents/UFRJ/8° Período/Otimização/Trabalhos/Trabalho Prático/cos360_optimization_implementation_assignment/objective_function_util.py:7: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(np.log(prod + 1))
