In [1]:
import random
import numpy as np

from algorithms import Gradiente, Newton_1D, Newton_ND, BFGS

from objective_function_util import f, gradient_f, hessian_f

In [2]:
noise = np.random.normal(0, 1, (2, 5))
print(noise)
print(noise.shape)
noise2 = np.random.normal(0, 1, noise.shape)
print(noise2)

[[-0.11112956 -0.55645757 -0.15350668 -2.38250818  0.37417762]
 [-0.74139359  0.55583296 -1.31198557  0.07721654 -1.19551535]]
(2, 5)
[[ 1.38730954 -1.41779908 -0.7495893   0.68642666 -0.16340809]
 [-0.15016996  1.06348877 -0.90858552  0.52452137  1.11900377]]


In [10]:
a = np.exp(5)
print(a)

148.4131591025766


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
b = a + np.random.normal(0, 1, a.shape)
print(b)

[[1 2 3]
 [4 5 6]]
[[1.34783613 2.60420559 2.03273351]
 [4.64223159 5.16972985 7.23131624]]


In [4]:
def prod(sample):
    out = 1
    for i in range(0, 5):
        out = out * sample[i] * (1 - sample[i])
    return out

def gen_sample():
    sample = []
    for i in range(0, 5):
        sample.append(random.uniform(-500, 500))
    while prod(sample) < 0:
        sample = []
        for i in range(0, 5):
            sample.append(random.uniform(-500, 500))
    return sample

In [5]:
samples = []

for i in range(0, 50):
    samples.append(gen_sample())

print(samples)

[[461.7186168014498, 347.346515666972, -386.39324187893664, 0.8612619724029855, -481.91006274403617], [7.965479792297799, -285.965364419013, 0.6540362663272958, 431.0368893365153, -93.47003705908787], [-371.9101997865645, 343.77259494013606, -20.15215357207535, 227.97361890924049, 0.8807648470681215], [0.33808461764715503, -462.7124098866675, -129.38845870276617, -384.13413790148167, 240.68552107533117], [-491.4379700284527, -305.43127184939203, 399.3022300969408, 0.08228173984679188, -63.59812678464817], [0.27716123910681745, 136.78712398496725, 437.03314063689425, 179.02694185082873, -250.23513826316622], [-28.3222734842671, 0.7686828415824039, 307.3553052381676, 214.89938537620264, 419.2941582909194], [73.52992475000303, -134.02997090584978, 0.09662122258049521, 327.5225122259998, -219.72817867997986], [276.02047350401324, 463.77331297568196, -283.972569304196, 0.5640418679428763, -35.68975040018694], [-90.99250860668997, -178.32576482731952, 368.4450005735031, -3.7091649447760346, 

In [6]:
for sample in samples:
    print(f(sample))

6.790792682945229
5.921257502282327
6.178392348428733
6.5863520551420365
6.446522373820632
6.465120118434925
6.265631405255589
6.189996816058431
6.371008514235452
5.717081833497219
6.280710508977803
6.36351980260089
6.0771832764443445
6.145918479474699
6.24341152244651
6.313431335089235
6.23804541191729
5.188363248584054
6.638679120031647
5.532776046551293
6.266233266638487
5.53448677643117
6.138993023185897
6.218847582928876
6.642632703756414
6.4957996993709655
5.867130194715282
5.850398415853174
6.748435930141195
6.247083347210779
6.030342710707158
6.260913536072633
6.5998742849849155
6.371436817834552
6.6251611659389065
6.680315298623568
6.328920410131572
6.020804735974446
6.420280693232815
6.060186254190798
6.69719816946604
5.92804518066208
5.413125666227825
6.647735895905089
6.360549098133842
6.705748697513431
6.0669217953154755
6.37724998809179
6.401068056836073
6.545658664460856


In [7]:
x = np.array([0.5, 3, 8, 6, 7])

print(f(x))
print(gradient_f(x))
print(hessian_f(x))

print(np.linalg.det(hessian_f(x)))
print(np.linalg.norm(hessian_f(x)))

3.401425178799019
[0.         0.12249767 0.03937425 0.05389898 0.04549914]
[[-0.2939916356527391, -0.5005743444700167, -0.1608988964367911, -0.22025271156680737, -0.18592761366029195], [-0.0, 0.34495441772361296, -0.026815707719234857, -0.036707724344552606, -0.030987040031115836], [-0.0, -0.03127775881695764, 0.32213491581731474, -0.01376221387946136, -0.011617453274869979], [-0.0, -0.04170869366463398, -0.013406365820775205, 0.32450814401556966, -0.015491800504006904], [-0.0, -0.035748324803610926, -0.011490532972589222, -0.015729262913588803, 0.3230476958935666]]
-0.003290024872757404
0.941568092821632


In [8]:
x = np.array([0.5, 3, 8, 6, 7])

xf = Gradiente(f, gradient_f, x, 11000)

print(xf)
print(f(xf))

xf = Newton_ND(f, gradient_f, hessian_f, x, 11000)

print(xf)
print(f(xf))

dimensions = 5

xf = BFGS(f, gradient_f, x, dimensions, 11000)

print(xf)
print(f(xf))

Armijo calls:13
[0.5        0.48663109 7.57377982 5.40184394 6.5028746 ]
nan
Nan value in matrix Hf_inv
[1.60720175 2.58740602 7.82024297 5.76369113 6.79559939]
nan
Nan value in matrix p or q.
[-1.17086925e+12  3.42828749e+12 -5.81266686e+12  1.18491579e+12
  2.37033284e+12]
nan


/var/home/pc-146/Documents/UFRJ/8° Período/Otimização/Programs/objective_function_util.py:7: RuntimeWarning: invalid value encountered in log
  return np.sqrt(np.log(prod + 1))
/var/home/pc-146/.conda/envs/work_env/lib/python3.12/site-packages/numpy/linalg/linalg.py:2180: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


In [9]:
for i in range(0, 50):
    print(f"Test for sample {i}")

    # x = np.array([0.5, 3, 8, 6, 7])
    x = samples[i]

    print("Results for gradient")
    xf = Gradiente(f, gradient_f, x, 11000)

    print(xf)
    print(f(xf))

    print("Results for newton")
    xf = Newton_ND(f, gradient_f, hessian_f, x, 11000)

    print(xf)
    print(f(xf))

    dimensions = 5

    print("Results for BFGS")
    xf = BFGS(f, gradient_f, x, dimensions, 11000)

    print(xf)
    print(f(xf))

Test for sample 0
Results for gradient
Armijo calls:4
[ 461.71829752  347.3460911  -386.39286126    1.3064782  -481.90975749]
nan
Results for newton
Nan value in matrix Hf_inv
[ 4.61728641e+02  3.47359840e+02 -3.86405227e+02 -8.12241933e-02
 -4.81919672e+02]
nan
Results for BFGS
Nan value in matrix p or q.
[nan nan nan nan nan]
nan
Test for sample 1
Results for gradient
Armijo calls:5
[   7.9198811  -285.96418323    1.02566212  431.03610342  -93.46643613]
nan
Results for newton
Nan value in matrix Hf_inv
[ 8.58787258e+00 -2.85984314e+02 -7.41285539e-02  4.31049442e+02
 -9.35281037e+01]
nan
Results for BFGS
Nan value in matrix p or q.
[nan nan nan nan nan]
nan
Test for sample 2
Results for gradient
Armijo calls:4
[-371.90976517  343.77212344  -20.14431181  227.97290738    1.46760129]
nan
Results for newton
Nan value in matrix Hf_inv
[-3.71926085e+02  3.43789772e+02 -2.04446763e+01  2.27999517e+02
 -8.27146643e-02]
nan
Results for BFGS
Nan value in matrix p or q.
[nan nan nan nan nan]
na