In [9]:
import random
import numpy as np

from algorithms import Gradiente, Newton_1D, Newton_ND, BFGS

from obj_test_util3 import f, gradient_f, hessian_f
from objective_function_util import f as obj_fn

In [10]:
def prod(sample):
    out = 1
    for i in range(0, 5):
        out = out * sample[i] * (1 - sample[i])
    return out

def gen_sample():
    sample = []
    for i in range(0, 5):
        sample.append(random.uniform(0, 1))
    while prod(sample) < 0:
        sample = []
        for i in range(0, 5):
            sample.append(random.uniform(0, 1))
    return sample

In [11]:
samples = []

for i in range(0, 5):
    samples.append(gen_sample())

print(samples)

[[0.005289713590717282, 0.6539392394820442, 0.09013656667944903, 0.384749166322914, 0.9166973975623443], [0.7354231959293692, 0.6802548039404966, 0.8594646311424649, 0.42944788437534054, 0.5686226298698073], [0.061936008597879066, 0.9395866196194674, 0.20348722225059224, 0.017913578463483293, 0.8851348248630103], [0.8289382772030963, 0.7638255820312797, 0.8089602043444323, 0.8340738586940017, 0.2714008688867715], [0.10048924211248822, 0.6963408183837947, 0.390235609239038, 0.19637977929262895, 0.615489410129534]]


In [12]:
k = 100

for i in range(0, 5):
    print(f"Test for sample {i}")

    # x = np.array([0.5, 3, 8, 6, 7])
    x = samples[i]

    print("Calling gradient")
    xf = Gradiente(f, gradient_f, x, k)

    print(xf)
    print(f"Gradient result: {f(xf)}")

    print("Calling newton")
    xf = Newton_ND(f, gradient_f, hessian_f, x, k)

    print(xf)
    print(f"Newton result: {f(xf)}")

    dimensions = 5

    print("Calling BFGS")
    xf = BFGS(f, gradient_f, x, dimensions, k)

    print(xf)
    print(f"BFGS result: {f(xf)}")

Test for sample 0
Calling gradient
Armijo calls:100
[-0.02981357  0.65337465  0.09419271  0.38515337  0.91228621]
Gradient result: nan
Calling newton
[1.60126351e-04 9.63156644e-01 3.27545338e-03 5.64774447e-02
 9.97022955e-01]
Newton result: 1.7127910906661122e-06
Calling BFGS
Else.
Matrix Hf is singular.
[ 3.19366217  0.67320972 -2.06601743  0.39102628 -0.14948013]
BFGS result: nan
Test for sample 1
Calling gradient
Armijo calls:100
[0.75834513 0.69563788 1.07223228 0.42418764 0.57373278]
Gradient result: nan
Calling newton
[1.16335883 1.07625923 1.18614865 0.23600303 0.75718188]
Newton result: nan
Calling BFGS
Else.
Matrix Hf is singular.
[0.83955751 0.73217329 0.91447108 0.41708423 0.58058736]
BFGS result: 0.011059012491860618
Test for sample 2
Calling gradient
Armijo calls:100
[0.06071123 0.94084527 0.20319287 0.01276563 0.88574556]
Gradient result: 0.000809544977407279
Calling newton
[0.00476475 0.99536406 0.02133486 0.00128807 0.99026754]
Newton result: 2.3800377972264287e-06
Ca

/var/home/pc-146/Documents/UFRJ/8° Período/Otimização/Trabalhos/Trabalho Prático/cos360_optimization_implementation_assignment/objective_function_util.py:7: RuntimeWarning: invalid value encountered in sqrt
  return np.sqrt(np.log(prod + 1))


Else.
Matrix Hf is singular.
[0.83142678 0.76538905 0.81110171 0.83666459 0.27016611]
BFGS result: 0.010193076128198541
Test for sample 4
Calling gradient
Armijo calls:100
[-0.06254122  0.70338513  0.38675922  0.18137418  0.61916802]
Gradient result: nan
Calling newton
[-0.01274678  0.88113903  0.26221828  0.01652724  0.74879777]
Newton result: nan
Calling BFGS
Else.
Matrix Hf is singular.
[-0.0647972   0.78001328  0.35021116 -0.00886842  0.65789704]
BFGS result: 0.002329212062060926
